services:
  database:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: tony
      POSTGRES_DB: anonymizer
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data